/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ezioSol from "./EZIO.sol";
export type { ezioSol };
import type * as xEzioSol from "./xEZIO.sol";
export type { xEzioSol };
export type { EzioPublicSale } from "./EzioPublicSale";
